### PR TITLE
Adding intel_pstate information

### PR DESCRIPTION
**Pull request by bmichalo**
Adding intel_pstate driver information

### CODE REVIEW

**Review by k-rister — CHANGES_REQUESTED** [review]
Given that we already have the `collect_cpu_info` function I think I would prefer to see this be included as part of that rather than creating a whole new collector.  It's not really about trying to avoid adding collectors, it's more about logging the information in a logical place relative to other information that is already being collected.

**Comment by bmichalo** [comment]
Updated - thx Karl

**Review by k-rister — CHANGES_REQUESTED** [review]
Everything looks fine except the indentation is messed up.  Can you fix that?

**Review by k-rister — CHANGES_REQUESTED** [review]
The new stuff looks fine, but something is wrong with the old stuff.  I would just not touch that (use `git checkout -p`).

**Review by k-rister — APPROVED** [review]

**Pull request merged**
